apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: hello-go
build:
  artifacts:
  - image: gcr.io/k8s-tests-999/go-app
deploy:
  kubectl:
    manifests:
    - k8s/app-depl.yaml
    - k8s/app-svc.yaml
