apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: gcr.io/k8s-tests-999/go-app
        ports:
        - containerPort: 8080

