apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app
  name: go-svc
  namespace: default
spec:
  type: LoadBalancer  
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: go-app